language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php: [7.3, 7.4, 8.0]

env:
  - WEBDRIVER=selenium

matrix:
  allow_failures:
    - env: 'WEBDRIVER=phantomjs'
    - env: WEBDRIVER=phantomjs PHANTOM_VERSION=2
  fast_finish: true
  include:
    - php: 7.3
      env: WEBDRIVER=phantomjs
    - php: 7.4
      env: WEBDRIVER=phantomjs PHANTOM_VERSION=2
    - php: 8.0
      env: WEBDRIVER=selenium-remote
      sudo: required
      services:
        - docker

before_script:
  - sh bin/run-"$WEBDRIVER".sh

  - composer install

  # Start a webserver for web fixtures.
  - MINK_PHP_BIN=~/.phpenv/versions/7.3/bin/php vendor/bin/mink-test-server > /dev/null 2>&1 &

script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat /tmp/webdriver_output.txt
